title: Matt McCormick
description: "My name is Matt McCormick and I'm a Program Manager at Microsoft and a Computer Science graduate from Purdue University. I live in Seattle with my wife and our dog and I'm always hacking away on something."
language: en-us

author: Matt McCormick
email: matt@mbmccormick.com

permalink: articles/:year/:month/:title

gems:
  - jekyll-sitemap

exclude:
  - CNAME
  - Gemfile
  - LICENSE.txt
  - README.md

google:
  analytics:
    profile: 'UA-6872595-6'

disqus:
  shortname: mbmccormick

twitter:
  username: mbmccormick

linkedin:
  username: mbmccorm
